feat: api ipfs path
nftstorage/nft.storage pull request #1064
Opened 2022-01-12 18:13 UTC by vasco-santos

Add ipfs route to proxy CIDv0 to the gateway

Closes #1049 

Needs:

- #961

2022-01-17 12:34 UTC, alanshaw requested changes
Can we redirect instead of proxy? HTTP 302 response?

2022-01-18 18:18 UTC, vasco-santos commented
> Can we redirect instead of proxy? HTTP 302 response?

Yes :) I want to use redirect, but did not test yet

2022-01-19 14:00 UTC, alanshaw requested changes

2022-01-19 14:46 UTC, vasco-santos commented
@alanshaw forgot to mention, I am not a fan of using real production services for testing. The issue here is using subdomains, which make it difficult to spin smoke server or even run the gateway in Miniflare to use it as a testing backend...  basically DNS fails to resolve

2022-02-08 17:35 UTC, merged