feat: add stats page
nftstorage/nft.storage pull request #1376
Opened 2022-02-14 22:39 UTC by cmunns

also refactor logos component out of index.js, update footer with new link and space for heart icon
<img width="1508" alt="Screen Shot 2022-02-14 at 2 39 23 PM" src="https://user-images.githubusercontent.com/1189523/153958552-55f39b83-180f-4a3a-9f64-f6a33331614a.png">

2022-03-08 22:59 UTC, dashcraft commented
Using live data:
![image](https://user-images.githubusercontent.com/11915975/157340169-de6ea3ea-1242-4f01-86e1-8bc04875bd4f.png)

2022-03-09 13:58 UTC, Codigo-Fuentes requested changes
**todo (blocking):** Fix casing of marquee text.

Should be: "NFT.Storage"

<img width="554" alt="case" src="https://user-images.githubusercontent.com/43380153/157456034-aacef205-0509-4baf-8b04-2e15cfc7a9b6.png">

2022-03-09 14:00 UTC, Codigo-Fuentes commented
**issue (blocking):** There is an abrupt skip / jank when the marquee runs out of text. See video below.

https://user-images.githubusercontent.com/43380153/157456370-7ea9573a-95ae-4fb1-ba0f-0755fbfee4e1.mp4

2022-03-09 14:10 UTC, Codigo-Fuentes commented
**todo (blocking):** Fix case, formatting of number in stat cards. 

The case of the text between square brackets is inconsistent between the two cards. I suggest using title case--i.e., [Week over week change] and [Total deals]. I think this is most in keeping with overall style on the site.

The number of total deals should probably have a comma (e.g., 34,959) or use toLocaleString.

<img width="1255" alt="copy-issues" src="https://user-images.githubusercontent.com/43380153/157456711-ba629a15-db21-4db8-b9f2-d471c50fff06.png">

2022-03-09 18:39 UTC, Codigo-Fuentes requested changes
**issue (blocking):** Still getting jank on page load.

https://user-images.githubusercontent.com/43380153/157508972-a83fb10e-7d21-4207-bebc-bf7313705517.mp4


https://user-images.githubusercontent.com/43380153/157508981-047464cf-7055-4eac-b677-52925a7a700e.mp4

2022-03-09 18:43 UTC, Codigo-Fuentes commented
**todo:** Fix 1px white strips on sides of image with 3 arrows at top of card. Appears on Safari dt and mobile

![1px-white](https://user-images.githubusercontent.com/43380153/157509509-6105c318-9d27-4e5b-9afa-af0f92a0ef50.jpeg)

<img width="1680" alt="1px-white-dt" src="https://user-images.githubusercontent.com/43380153/157509488-04fd1cd5-6042-4f25-9fe1-da38335bf8d4.png">

2022-03-09 22:08 UTC, JeffLowe commented
Checked on device lab (iphone 8 safari & Android Chrome latest, as well as chrome desktop).  stats page looks good

2022-03-09 22:12 UTC, dashcraft commented on packages/client/test/lib.spec.js
> +      // @ts-ignore
This blows up the linter so we had to add it here to get the build to pass. It's in a spec file, so there are no negative downstream side effects we need to worry about.

2022-03-09 22:32 UTC, dashcraft approved these changes
Looking good! Good starting off point!

2022-03-09 22:46 UTC, merged