feat(docs): add UCAN how-to
nftstorage/nft.storage pull request #1705
Opened 2022-03-24 20:56 UTC by yusefnapora

This adds a new how-to doc for using UCAN, to close #1431.

There's a lot of copy/paste from the ucan.storage README, but I left out some of the more generic stuff like generating keypairs and just linked to the README docs for those. I figure that should be a bit less work if the ucan-storage API changes at all, and this how-to seems long enough without showing those examples. It does mean kicking the reader off to another page to get the complete picture though, so if anyone feels strongly about that we can copy that stuff over as well.

2022-03-29 10:39 UTC, hugomrdias requested changes

2022-03-29 10:39 UTC, hugomrdias commented on packages/website/pages/docs/how-to/ucan.md
> +The `aud` or "audience" field contains the public key that should _recieve_ the token.
```suggestion
The `aud` or "audience" field contains the public key that should _receive_ the token.
```

2022-03-29 10:39 UTC, hugomrdias commented on packages/website/pages/docs/how-to/ucan.md
> +The `upload/IMPORT` action allows access to upload a specific Content Archive (CAR), identified by the [multihash][multihash] of the CAR data.
```suggestion
```

i think we should remove the `mh` for now i dont know if we gonna support it yet

2022-03-29 10:39 UTC, hugomrdias commented on packages/website/pages/docs/how-to/ucan.md
> +{ /* TODO: show response body  */ }
do you want to add this before merging ?

2022-03-31 18:40 UTC, yusefnapora commented
Thanks for the review, @hugomrdias 👍

2022-04-01 15:59 UTC, merged