feat: update logo text and link to github
nftstorage/nft.storage pull request #1833
Opened 2022-04-15 23:20 UTC by johnathonroach

Fixes #1686
This PR updates the count from 20,000 to 30,000 logo users and adds a link to the github discussion page where users may upload their own logo to be used on the site.

2022-04-20 16:27 UTC, Codigo-Fuentes requested changes
**issue (ux,blocking)**: The link text, "here" should be visually distinct from the rest of the surrounding text and identifiable as a link on sight.

2022-04-20 16:32 UTC, Codigo-Fuentes commented
**suggestion(non-blocking)** The copy reads slightly awkward imo.

my suggestion: "Request to add your logo [here](https://github.com/nftstorage/nft.storage/discussions/1474)"

2022-04-21 11:03 UTC, Codigo-Fuentes commented
**suggestion:** Remove full stop from "Request your logo here." text

2022-04-21 11:11 UTC, Codigo-Fuentes commented
**todo:** Update link color so that it has sufficient contrast.

I suggest using nsnavy var which is used for the other link on the page.

### nsblue: contrast ratio 2.32 🚫
<img width="1260" alt="nsblue" src="https://user-images.githubusercontent.com/43380153/164445457-60d73ad1-bc02-404e-bb4a-037367b9ab3a.png">

### nsnavy: contrast ratio 5 ✅
<img width="1260" alt="nsnavy" src="https://user-images.githubusercontent.com/43380153/164445438-d68cbe3e-f228-4bbe-a875-e97ffb8add01.png">

2022-04-22 16:40 UTC, cmunns approved these changes
Some minor items from @Codigo-Fuentes that could get changed, but non blocking imo.

2022-04-25 12:14 UTC, Codigo-Fuentes approved these changes

2022-04-25 21:38 UTC, merged