fix: add incidents to banner
nftstorage/nft.storage pull request #1834
Opened 2022-04-16 15:04 UTC by johnathonroach

Fixes #1728
This PR adds incidents notices to the NFT.storage banner. If there is an incident, it will take precedence over maintenance notices.

2022-04-19 17:44 UTC, cmunns requested changes

2022-04-19 17:44 UTC, cmunns commented on packages/website/components/layout.js
> +        incident.resolved_at === null
Unless we are certain it will be null it can't hurt to check for falsey values including empty string here.

2022-04-20 16:51 UTC, alanshaw requested changes

2022-04-20 16:51 UTC, alanshaw commented on packages/website/components/layout.js
> +    ) || []
```suggestion
    (statusPageData?.incidents || []).filter(
      (/** @type {{ resolved_at: string; }} */ incident) => !!incident.resolved_at)
```

2022-04-22 16:36 UTC, cmunns approved these changes
LGTM

2022-04-26 16:17 UTC, alanshaw approved these changes

2022-04-27 22:24 UTC, johnathonroach commented
@alanshaw do you know if there is a way we can test a mock incident within the preview environment? The data for prod comes from https://status.nft.storage/api/v2/. I'm curious if there is a staging version of this endpoint to test with before we merge.

2022-04-29 12:50 UTC, alanshaw commented
Create a new free statuspage.io account and create a status page that we can wire up to the staging deployment in order to test. Add me as an admin.

2022-05-02 18:21 UTC, johnathonroach commented
@alanshaw statuspage account has been created at https://nftstorage-jroach.statuspage.io/api/v2. I have added you as an admin. 

The app is wired up to use the env var `NEXT_PUBLIC_STATUS_PAGE_API` and will fall back to the original endpoint( (https://status.nft.storage/api/v2) when it is not set.

2022-05-03 22:31 UTC, merged