fix: preserve all backup_urls for chunked uploads
nftstorage/nft.storage pull request #1940
Opened 2022-05-24 18:20 UTC by yusefnapora

This stops the bleeding on #1939 by making sure we append to `upload.backup_urls` instead of overwriting when updating an existing entry.

Once this is in, we'll need to do the migration to backfill the missing backup_urls from the time after #1664 was merged. I've started working on that but likely won't finish today.

2022-05-25 08:47 UTC, vasco-santos requested changes
Overall looking good, thanks @yusefnapora 
I guess we don't need `s3-scrape-backup-urls.js` file right?

2022-05-25 08:47 UTC, vasco-santos commented on packages/api/test/nfts-upload.spec.js
> +    console.log('chunked car root cid:', root.toString())
```suggestion
```

2022-05-25 18:17 UTC, vasco-santos approved these changes
LGTM

2022-05-26 10:23 UTC, hugomrdias approved these changes

2022-05-26 18:09 UTC, merged