feat(utils): add timers to logging
nftstorage/nft.storage pull request #2151
Opened 2022-08-24 15:03 UTC by ericssontadashi

migrating from web3 logging

2022-09-02 14:24 UTC, vasco-santos reviewed
The set of changes look good to me, but would be great to know more about the motivation of this PR, so that I can better support in case other solutions exist.

As a side note, I would really prefer if we simply drop this file and used the common code in workers/utils https://github.com/web3-storage/workers/blob/master/packages/utils/src/logging.js

From what I see, it already has what is in here?

2022-09-05 16:54 UTC, alanshaw requested changes

2022-09-05 16:54 UTC, alanshaw commented on packages/api/src/utils/logs.js
> -    return timeObj
No return statement anymore?

2022-09-05 16:54 UTC, alanshaw commented on packages/api/src/utils/logs.js
> +  timeEnd(name, shouldLog, context) {
This should match the [`timeEnd`](https://developer.mozilla.org/en-US/docs/Web/API/console/timeEnd) method.

2022-09-05 16:54 UTC, alanshaw commented on packages/api/src/utils/logs.js
> +    if (shouldLog) {
Note that timing execution is not effective in production and I believe that is why this method does not send logs to logtail.

https://developers.cloudflare.com/workers/learning/security-model/#step-1-disallow-timers-and-multi-threading

2022-09-13 09:22 UTC, hugomrdias commented
yes @ericssontadashi exactly what @vasco-santos said drop this file and use https://github.com/web3-storage/workers/blob/master/packages/utils/readme.md#logging directly if you have problems or questions doing that ping me

2023-02-14 13:09 UTC, closed without merging