fix: fix typescript nodenext resolution
nftstorage/nft.storage pull request #2185
Opened 2022-09-14 19:14 UTC by rayzr522

tiny fix here: while your ESModule build is working totally fine, when downstream consumers are set up to use `nodenext` for their `module` & `moduleResolution` settings, typescript reads your `package.json` and sees that the `exports.node` points to the `src` folder and tries to also look there for the typescript typings

as per [the typescript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) this just lets typescript know to still keep looking in the `dist/src` folder for the types :)

2022-10-27 18:47 UTC, rayzr522 commented
bump! could we get this merged?

2022-10-27 20:46 UTC, alanshaw requested changes

2022-10-27 20:46 UTC, alanshaw commented on packages/client/package.json
> +      "types": "./dist/src/platform.cjs",
```suggestion
      "types": "./dist/src/platform.d.ts",
```

2022-10-27 20:46 UTC, alanshaw commented on packages/client/package.json
> +      "types": "./dist/src/token.cjs",
```suggestion
      "types": "./dist/src/token.d.ts",
```

2023-01-12 22:57 UTC, rayzr522 commented
@alanshaw thanks for the review! can't believe I missed it til now, and all just because of such a silly typo hehe

rebased on main & made the changes you requested :3

2023-01-13 20:39 UTC, alanshaw approved these changes

2023-01-13 20:40 UTC, merged